### ISSUE TITLE
npm run build is not generating a tree-shaken build.js

### ISSUE THREAD

**Issue by perrohunter** [Stanko/react-redux-webpack2-boilerplate#2] opened 2016-12-11 04:57 UTC
I'm trying to get the project to product a more lightweight build, however the output of `npm run build` is about 2.5MB, which is a little bit too much, seems like webpack 2.1 beta 26 broke this

**Comment by Stanko** [comment] 2017-03-10 13:28
Hey, good catch, I will look into this, do you maybe know where the issue is?

**Comment by Stanko** [comment] 2017-04-25 15:07
Fixed with the last update, thanks!

**Closed by Stanko** 2017-04-25 15:07 UTC
